language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - "node_modules"
script:
- "npm run lint"
- "npm test"
- "npm run build"
